# Project metadata and distribution rules for the Amnesia Agent Ren'Py client.

define config.name = "Amnesia Agent"
define config.version = "0.0.0-alpha.0"
define config.save_directory = "amnesia-agent"
define build.name = "amnesia-agent"
define build.version = "0.0.0-alpha.0"

init python:
    # The native local-server sidecar is generated by CI and must remain an
    # unpacked executable next to the game's other files.
    build.classify("game/server/**", "all")
    build.executable("game/server/**")
