import { Check, RefreshCw } from 'lucide-react';
import type { Config } from '../../../shared/types';
import { Field } from '../../components/Field';
import { IconButton } from '../../components/IconButton';
import { useI18n } from '../../i18n/i18n';
import type { SettingsForm } from '../../lib/settings';

export function SettingsView({ form, setForm, config, save, reset }: { form: SettingsForm; setForm: (form: SettingsForm) => void; config: Config | null; save: () => Promise<void>; reset: () => Promise<void> }) {
  const { t } = useI18n();
  const update = (key: keyof SettingsForm, value: string) => setForm({ ...form, [key]: value });
  return <div className="mx-auto max-w-3xl space-y-5 overflow-y-auto pb-8"><section className="rounded-lg border border-slate-800 bg-slate-900/50 p-4 sm:p-5"><div className="mb-5"><h2 className="font-medium">{t('provider')}</h2><p className="mt-1 text-xs text-slate-500">{t('providerHint')}{config?.api_key_set ? ' ✓' : ''}</p></div><div className="grid gap-4 sm:grid-cols-2"><Field label={t('model')} value={form.model} onChange={(value) => update('model', value)} placeholder="provider/model" /><Field label={t('apiKey')} value={form.apiKey} onChange={(value) => update('apiKey', value)} placeholder={t('keepCurrentKey')} type="password" /><Field label={t('baseUrl')} value={form.baseUrl} onChange={(value) => update('baseUrl', value)} placeholder="https://…" /><div className="sm:col-span-2"><label className="mb-1.5 block text-xs text-slate-400">{t('providerParams')}</label><textarea aria-label={t('providerParams')} value={form.providerParams} onChange={(event) => update('providerParams', event.target.value)} rows={5} className="field w-full font-mono text-xs" /></div></div></section><section className="rounded-lg border border-slate-800 bg-slate-900/50 p-4 sm:p-5"><div className="mb-5"><h2 className="font-medium">{t('executionLimits')}</h2><p className="mt-1 text-xs text-slate-500">{t('executionHint')}</p></div><div className="grid gap-4 sm:grid-cols-3"><Field label={t('commandTimeout')} value={form.timeout} onChange={(value) => update('timeout', value)} type="number" /><Field label={t('maxOutput')} value={form.outputLimit} onChange={(value) => update('outputLimit', value)} type="number" /><Field label={t('maxContext')} value={form.contextLimit} onChange={(value) => update('contextLimit', value)} type="number" /></div></section><div className="flex justify-end gap-1"><IconButton label={t('restoreDefaults')} onClick={() => void reset()} className="text-slate-400 hover:bg-slate-800"><RefreshCw size={16} /></IconButton><IconButton label={t('save')} onClick={() => void save()} className="bg-cyan-400 text-slate-950 hover:bg-cyan-300"><Check size={16} /></IconButton></div></div>;
}
